import uuid
from sqlalchemy import Column, String, DateTime, Boolean
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.sql import func
from app.core.database import Base

class User(Base):
    __tablename__ = "users"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    email = Column(String, unique=True, index=True, nullable=False)
    password_hash = Column(String, nullable=False)
    first_name = Column(String, nullable=False)
    last_name = Column(String, nullable=False)
    # Generated by backend
    full_name = Column(String, nullable=True) 
    # Set the defualt role to buyer
    role = Column(String, nullable=False, default="buyer")
    # Timestamp of user creation
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    # To verify email
    is_verified = Column(Boolean, default=False)