import uuid
from sqlalchemy import Column, String, DateTime
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.sql import func
from app.core.database import Base

class User(Base):
    __tablename__ = "users"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    email = Column(String, unique=True, index=True, nullable=False)
    password_hash = Column(String, nullable=False)
    
    first_name = Column(String, nullable=False)
    last_name = Column(String, nullable=False)
    full_name = Column(String, nullable=True) # Generated by backend
    
    # We don't strictly need a default here because the DB handles it, 
    # but it's good practice for the code to know "buyer" is the default.
    role = Column(String, nullable=False, default="buyer")
    
    created_at = Column(DateTime(timezone=True), server_default=func.now())